apiVersion: v1
kind: Pod
metadata:
  name: redis-client-pod
  namespace: app-sandbox
spec:
  nodeName: worker-3
  containers:
  - name: redis-client-pod
    image: airdock/redis-client
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
    resources:
      requests:
        cpu: "0.5"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"

