apiVersion: v1
kind: Pod
metadata:
  name: ssh-client-pod
  namespace: omid
spec:
  containers:
  - name: ssh-client-pod
    image: instrumentisto/rsync-ssh:alpine3.21-r3
    command: ["/bin/sh"]
    args: ["-c", "while true; do ping localhost; sleep 6000;done"]
    resources:
      requests:
        cpu: "0.5"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
