apiVersion: v1
kind: Pod
metadata:
  name: omid-test
  namespace: mynamespace
spec:
  #nodeName: k3s-worker-1
  containers:
  - name: omid-test
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
    resources:
      requests:
        cpu: "0.5"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
